name: build-macos

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install . pyinstaller
      - name: Build app bundle
        run: |
          pyinstaller --noconfirm --windowed --name Sanitize \
            --add-data "assets/ui/index.html:assets/ui/index.html" \
            src/sanitize/app.py
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Sanitize-macos
          path: dist/Sanitize.app/**
          if-no-files-found: error
